repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: poetry-task-format
        name: run poetry task format
        entry: bash
        language: system
        args: ['-c', 'poetry shell && poetry run task format']
        types: [python]

#   Executando o task format
# - repo: https://github.com/psf/black-pre-commit-mirror
#   rev: 24.4.2
#   hooks:
#     - id: black
#       language_version: python3.11
# - repo: https://github.com/pycqa/isort
#   rev: 5.13.2
#   hooks:
#     - id: isort
#       name: isort (python)
# - repo: https://github.com/pycqa/flake8
#   rev: 7.0.0
#   hooks:
#     - id: flake8
