version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: BACEN
    ports:
      - "5437:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/create_table_postgres.sql:/docker-entrypoint-initdb.d/init.sql

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    volumes:
      - ./sql/create_table_mssql.sql:/scripts
    command: /bin/bash -c "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Pass@word -d master -i /scripts/create_database.sql"